apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/learnk8s/f5-microservices-march-three
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOSTNAME
              value: db
            - name: MYSQL_USER
              value: dbuser
            - name: MYSQL_PASSWORD
              value: dbpassword
            - name: MYSQL_DATABASE
              value: sqlitraining
        - name: proxy # <-- sidecar
          imagePullPolicy: Never
          image: "nginx"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: sidecar
